---
name: PHP-Session-DBI
version: 0.24
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Interface to PHP DataBase Sessions
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-php-session-dbi/
build_requires:
  Test::More: 0.40
requires:
  DBI: 0
  PHP::Session: 0.26
recommends:
  DBD::mysql: 0
configure_requires:
  Module::Build: 0.35
provides:
  PHP::Session::DBI:
    file: lib/PHP/Session/DBI.pm
    version: 0.24
no_index:
  directory:
    - monolithic_version
    - builder
    - t
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
